

query SearchRepo($query:String!,$type:SearchType!){ 
  search(first:20,query:$query,type:$type){
    nodes{
    ...on Repository {
      name,
      totalIssues:issues(states:OPEN){
        totalCount
      },
      labels(first:10){
        nodes{
          color,
          name,
          issues(states:OPEN){
            totalCount,
            
          }
        }
      }
    }
  }
  }
}

# Type queries into this side of the screen, and you will 
# see intelligent typeaheads aware of the current GraphQL type schema, 
# live syntax, and validation errors highlighted within the text.

# We'll get you started with a simple query showing your username!
query Search($query:String!,$type:SearchType!){ 
  search(type:$type,query:$query,first:10){
    
    nodes{
      ... on Repository{
        description,
        url,
        name,
        ... on RepositoryInfo{
          openGraphImageUrl
        }
        
        labels(first:5){
          totalCount,
          nodes{
            
            color,
            name,
            url
          }
        }
      }
    }
  }
}